Proyectos/Ejemplo/EjemploA/Apps/home/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView,AdministradoresView,EstudiantesView,CrearEstudiantesView,CrearEstudianteAutsView,CrearArticulosView,CrearComentariosView,CrearAdministradoresView,IniciosesionView,RegistroView,LoginView,ListarEstudiantesView,ListarEstudianteAutsView,ListarArticulosView,ListarComentariosView,ListarAdministradoresView,EditarEstudiantesView,EditarEstudianteAutsView,EditarArticulosView,EditarComentariosView,EditarAdministradoresView
from Apps.home import views

app_name='home'

urlpatterns = [
    path('',HomeView.as_view(), name='homeapp'),
    path('administradores/',AdministradoresView.as_view(), name='administradoresapp'),
    path('estudiantes/',EstudiantesView.as_view(), name='estudiantesapp'),
    path('crearestudiantes/',CrearEstudiantesView.as_view(), name='crearestudiantesapp'),
    path('crearestudianteauts/',CrearEstudianteAutsView.as_view(), name='crearestudianteautsapp'),
    path('creararticulos/',CrearArticulosView.as_view(), name='creararticulosapp'),
    path('crearcomentarios/',CrearComentariosView.as_view(), name='crearcomentariosapp'),
    path('crearadministradores/',CrearAdministradoresView.as_view(), name='crearadministradoresapp'),
    path('iniciosesion/',IniciosesionView.as_view(), name='iniciosesionapp'),
    path('registro/',RegistroView.as_view(), name='registroapp'),
    path('login/',LoginView.as_view(), name='loginapp'),
    path('listarestudiantes/',ListarEstudiantesView.as_view(), name='listarestudiantesapp'),
    path('listarestudianteauts/',ListarEstudianteAutsView.as_view(), name='listarestudianteautsapp'),
    path('listararticulos/',ListarArticulosView.as_view(), name='listararticulosapp'),
    path('listarcomentarios/',ListarComentariosView.as_view(), name='listarcomentariosapp'),
    path('listaradministradores/',ListarAdministradoresView.as_view(), name='listaradministradoresapp'),
    path('editarestudiantes/<int:pk>',EditarEstudiantesView.as_view(), name='editarestudiantesapp'),
    path('editarestudianteauts/<int:pk>',EditarEstudianteAutsView.as_view(), name='editarestudianteautsapp'),
    path('editararticulos/<int:pk>',EditarArticulosView.as_view(), name='editararticulosapp'),
    path('editarcomentarios/<int:pk>',EditarComentariosView.as_view(), name='editarcomentariosapp'),
    path('editaradministradores/<int:pk>',EditarAdministradoresView.as_view(), name='editaradministradoresapp'),

    
]

Proyectos/Ejemplo/EjemploA/EjemploA/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Proyectos/Ejemplo/EjemploA/Apps/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


# Create your models here.

class Estudiante(models.Model):
    nombre= models.CharField(max_length=100)
    apellido= models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)

class Curso(models.Model):
    nombre= models.CharField(max_length=100)
    creacion = models.DateTimeField(auto_now_add = True)
    Estudiante = models.ManyToManyField(Estudiante)

    def __str__(self):
        return '%s' % (self.nombre)

class Telefono(models.Model):
    tipo_telefono = (
        ('C', 'Casa'),
        ('M', 'Movil'),
        ('T','Trabajo'),
    )
    telefono= models.CharField(max_length=13)
    estudiante = models.ForeignKey(Estudiante,on_delete = models.CASCADE)
    tipo = models.CharField(
        max_length= 1,
        choices = tipo_telefono,
        default = 'C',
    )
    creacion = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s' % (self.telefono)

class EstudianteAut(models.Model):
    nombre= models.CharField(max_length=100)
    apellido= models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)

class Articulo(models.Model):
    nombre= models.CharField(max_length=100)
    descripcion= models.CharField(max_length=100)
    creacion = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s %s' % (self.nombre, self.descripcion)

class Comentario(models.Model):
    comentario = models.CharField(max_length=100)
    Estudiante = models.ManyToManyField(Estudiante)
    Articulo = models.ManyToManyField(Articulo)
    creacion = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s' % (self.comentario)

class Administrador(models.Model):
    nombre= models.CharField(max_length=100)
    apellido= models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)

class Iniciosesion(models.Model):
    usuario = models.CharField(max_length=100)
    contrasena = models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s %s' % (self.usuario, self.contrasena)

class Usuario(models.Model):
    perfil = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.perfil.username

@receiver(post_save, sender=User)
def crear_usuario(sender, instance, created, **kwargs):
    if created:
        Usuario.objects.create(perfil=instance)

@receiver(post_save, sender=User)
def guardar_usuario(sender, instance, created, **kwargs):
    instance.usuario.save()

Proyectos/Ejemplo/EjemploA/Apps/home/forms.py
from django import forms
from .models import Estudiante, EstudianteAut, Articulo, Comentario, Administrador, Iniciosesion
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__'

class EstudianteAutForm(forms.ModelForm):
    class Meta:
        model = EstudianteAut
        fields = '__all__'

class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = '__all__'

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'

class AdministradorForm(forms.ModelForm):
    class Meta:
        model = Administrador
        fields = '__all__'

class IniciosesionForm(forms.ModelForm):
    class Meta:
        model = Iniciosesion
        fields='__all__'

class RegistroForm(UserCreationForm):
    first_name = forms.CharField(max_length=140, required=True)
    last_name = forms.CharField(max_length=140, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields=(
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

Proyectos/Ejemplo/EjemploA/Apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, UpdateView
from .forms import EstudianteForm, EstudianteAutForm, ArticuloForm, ComentarioForm, AdministradorForm, IniciosesionForm, RegistroForm
from django.urls import reverse_lazy 
from .models import Usuario, Estudiante, EstudianteAut, Articulo, Comentario, Administrador
from django.contrib.auth.views import LoginView

# Create your views here.

class HomeView(TemplateView):
    template_name='home.html'

class AdministradoresView(TemplateView):
    template_name='administradores.html'

class EstudiantesView(TemplateView):
    template_name='estudiantes.html'

class CrearEstudiantesView(CreateView):
    template_name='crearestudiantes.html'
    form_class = EstudianteForm
    success_url = reverse_lazy('home:listarestudiantesapp')

class EditarEstudiantesView(UpdateView):
    template_name='editarestudiantes.html'
    model = Estudiante
    form_class = EstudianteForm
    success_url = reverse_lazy('home:listarestudiantesapp')

class CrearEstudianteAutsView(CreateView):
    template_name='crearestudianteauts.html'
    form_class = EstudianteAutForm
    success_url = reverse_lazy('home:listarestudianteautsapp')

class EditarEstudianteAutsView(UpdateView):
    template_name='editarestudianteauts.html'
    model = EstudianteAut
    form_class = EstudianteAutForm
    success_url = reverse_lazy('home:listarestudianteautsapp')

class CrearArticulosView(CreateView):
    template_name='creararticulos.html'
    form_class = ArticuloForm
    success_url = reverse_lazy('home:listararticulosapp')

class EditarArticulosView(UpdateView):
    template_name='editararticulos.html'
    model = Articulo
    form_class = ArticuloForm
    success_url = reverse_lazy('home:listararticulosapp')

class CrearComentariosView(CreateView):
    template_name='crearcomentarios.html'
    form_class = ComentarioForm
    success_url = reverse_lazy('home:listarcomentariosapp')

class EditarComentariosView(UpdateView):
    template_name='editarcomentarios.html'
    model = Comentario
    form_class = ComentarioForm
    success_url = reverse_lazy('home:listarcomentariosapp')

class CrearAdministradoresView(CreateView):
    template_name='crearadministradores.html'
    form_class = AdministradorForm
    success_url = reverse_lazy('home:listaradministradoresapp')

class EditarAdministradoresView(UpdateView):
    template_name='editaradministradores.html'
    model = Administrador
    form_class = AdministradorForm
    success_url = reverse_lazy('home:listaradministradoresapp')

class IniciosesionView(TemplateView):
    template_name='iniciosesion.html'

class CrearIniciosesionView(CreateView):
    template_name ='iniciosesion.html'
    form_class = IniciosesionForm
    success_url=reverse_lazy('home:homeapp')

class RegistroView(CreateView):
    model = Usuario
    form_class = RegistroForm
    success_url=reverse_lazy('home:homeapp')

class LoginView(LoginView):
    template_name ='iniciosesion.html'

class ListarEstudiantesView(ListView):
    template_name='listarestudiantes.html'
    model = Estudiante

    def get_queryset(self):
        vNombre = self.request.GET.get('nombre')
        if(vNombre):
            return Estudiante.objects.filter(nombre__icontains=vNombre)
        else:
            return Estudiante.objects.all()

class ListarEstudianteAutsView(ListView):
    template_name='listarestudiantesauts.html'
    model = EstudianteAut
    
    def get_queryset(self):
        vNombre = self.request.GET.get('nombre')
        if(vNombre):
            return EstudianteAut.objects.filter(nombre__icontains=vNombre)
        else:
            return EstudianteAut.objects.all()

class ListarArticulosView(ListView):
    template_name='listararticulos.html'
    model = Articulo

    def get_queryset(self):
        vNombre = self.request.GET.get('nombre')
        if(vNombre):
            return Articulo.objects.filter(nombre__icontains=vNombre)
        else:
            return Articulo.objects.all()

class ListarComentariosView(ListView):
    template_name='listarcomentarios.html'
    model = Comentario

    def get_queryset(self):
        vNombre = self.request.GET.get('comentario')
        if(vNombre):
            return Comentario.objects.filter(comentario__icontains=vNombre)
        else:
            return Comentario.objects.all()

class ListarAdministradoresView(ListView):
    template_name='listaradministradores.html'
    model = Administrador

    def get_queryset(self):
        vNombre = self.request.GET.get('nombre')
        if(vNombre):
            return Administrador.objects.filter(nombre__icontains=vNombre)
        else:
            return Administrador.objects.all()

Proyectos/Ejemplo/EjemploA/Apps/home/templates/administradores.html
{% extends 'base.html' %}

{% block contenido %}
    <title>Administradores</title>

    <!-- Masthead-->
<header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center">
                <h1 class="mx-auto my-0 text-uppercase">ADMINISTRADORES</h1>
                <h2 class="text-white-50 mx-auto mt-2 mb-5">Pagina de tabla de administradores del sitio web</h2>
                <a class="btn btn-primary" href="#about">Aceptar</a>
                <a class="btn btn-primary" href={% url 'home:crearadministradoresapp' %}>Agregar Administradores</a>
                <a class="btn btn-primary" href="#about">Ocultar</a>
            </div>
        </div>
    </div>
</header>
<!-- About-->
<section class="about-section text-center" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8">
                <h2 class="text-white mb-4">Tabla de Estudiantes</h2>
                
            </div>
        </div>
        <img class="img-fluid" src="assets/img/ipad.png" alt="..." />
    </div>
</section>
    
    <table class="table">
        <tr>
            <td class="col-2 themed-grid-col">Id</td>
            <td class="col-4 themed-grid-col">Nombre</td>
            <td class="col-4 themed-grid-col">Apellido</td>
            <td class="col-3 themed-grid-col">Telefono</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Jake</td>
            <td>Peralta</td>
            <td>89482745</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Amy</td>
            <td>Santiago</td>
            <td>23493784</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Axl</td>
            <td>Rose</td>
            <td>29018371</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Raymond</td>
            <td>Holt</td>
            <td>91290192</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Freddie</td>
            <td>Merury</td>
            <td>10919238</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Jon</td>
            <td>Bon Jovi</td>
            <td>10932030</td>
        </tr>
        <tr>
            <td>7</td>
            <td>Walter</td>
            <td>White</td>
            <td>29090348</td>
        </tr>
        <tr>
            <td>8</td>
            <td>Jesse</td>
            <td>Pinkman</td>
            <td>13893847</td>
        </tr>
        <tr>
            <td>9</td>
            <td>Marie</td>
            <td>Schrader</td>
            <td>99391837</td>
        </tr>
        <tr>
            <td>10</td>
            <td>Gustavo</td>
            <td>Fring</td>
            <td>87737443</td>
        </tr>
    </table>

{% endblock %}

Proyectos/Ejemplo/EjemploA/Apps/home/templates/crearadministradores.html
{% extends 'base.html' %}

{% block contenido %}
<title>Crear Administrador</title>

    <!-- Masthead-->
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">CREAR ADMINISTRADORES</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">Pagina del formulario de Administradores del sitio web</h2>
                </div>
            </div>
        </div>
    </header>
    <!-- About-->
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                </div>
            </div>
        </div>
    </section>

    <section class="signup-section" id="signup">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-10 col-lg-8 mx-auto text-center">
                    <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                    
                    <h2 class="text-white mb-5">Formulario de ingreso de Administradores</h2>

                    <form class="form-signup" id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST">
                        <div class="text-white mb-5">
                            {% csrf_token %}
                            Nombre {{ form.nombre }}
                            Apellido {{ form.apellido }}
                        </div>    
                        <br><input class="btn btn-primary" id="submitButton" type="submit" name="Guardar">
                        &nbsp; <a class="btn btn-primary" href={% url 'home:administradoresapp' %}>Ver listado</a>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

Proyectos/Ejemplo/EjemploA/Apps/home/templates/crearcomentarios.html
{% extends 'base.html' %}

{% block contenido %}
<title>Crear Comentarios</title>

    <!-- Masthead-->
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">CREAR COMENTARIOS</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">Pagina del formulario de Comentarios del sitio web</h2>
                </div>
            </div>
        </div>
    </header>
    <!-- About-->
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                </div>
            </div>
        </div>
    </section>

    <section class="signup-section" id="signup">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-10 col-lg-8 mx-auto text-center">
                    <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                    
                    <h2 class="text-white mb-5">Formulario de ingreso de Comentarios</h2>

                    <form class="form-signup" id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST">
                        <div class="row input-group-newsletter">
                            {% csrf_token %}
                            Comentario {{ form.comentario }}
                            Estudiante {{ form.Estudiante }}
                            Articulo {{ form.Articulo }}
                        </div>  
                        <br><input class="btn btn-primary" id="submitButton" type="submit" name="Guardar">
                        &nbsp; <a class="btn btn-primary" href={% url 'home:listarcomentariosapp' %}>Ver listado</a>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

Proyectos/Ejemplo/EjemploA/Apps/home/templates/estudiantes.html
{% extends 'base.html' %}

{% block contenido %}
<title>Estudiantes</title>

    <!-- Masthead-->
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">ESTUDIANTES</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">Pagina de tabla de Estudiantes del sitio web</h2>
                    <a class="btn btn-primary" href="#about">Aceptar</a>
                    <a class="btn btn-primary" href={% url 'home:crearestudiantesapp' %}>Agregar Estudiantes</a>
                    <a class="btn btn-primary" href={% url 'home:crearestudianteautsapp' %}>Agregar Estudiantes Auts</a>
                    <a class="btn btn-primary" href="#about">Cancelar</a>
                </div>
            </div>
        </div>
    </header>
    <!-- About-->
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-white mb-4">Tabla de Estudiantes</h2>
                    
                </div>
            </div>
            <img class="img-fluid" src="assets/img/ipad.png" alt="..." />
        </div>
    </section>
  
    <table class="table">
        <tr>
            <td class="col-2 themed-grid-col">Id</td>
            <td class="col-4 themed-grid-col">Nombre</td>
            <td class="col-4 themed-grid-col">Apellido</td>
            <td class="col-3 themed-grid-col">Telefono</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Juan</td>
            <td>Garcia</td>
            <td>47563976</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Carlos</td>
            <td>Santana</td>
            <td>66483845</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Ana</td>
            <td>Lopez</td>
            <td>59376790</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Cameron</td>
            <td>Cuevas</td>
            <td>12039485</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Steve</td>
            <td>Gomez</td>
            <td>93222845</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Hank</td>
            <td>Schrader</td>
            <td>99948373</td>
        </tr>
        <tr>
            <td>7</td>
            <td>Saul</td>
            <td>Goodman</td>
            <td>58672227</td>
        </tr>
        <tr>
            <td>8</td>
            <td>Carmen</td>
            <td>Flores</td>
            <td>34933273</td>
        </tr>
        <tr>
            <td>9</td>
            <td>Rosa</td>
            <td>Diaz</td>
            <td>94826465</td>
        </tr>
        <tr>
            <td>10</td>
            <td>Terrance</td>
            <td>Jeffords</td>
            <td>32272737</td>
        </tr>
    </table>

{% endblock %}

Proyectos/Ejemplo/EjemploA/Apps/home/templates/home.html
{% extends 'base.html' %}

{% block titulo %}
    <h1 class="mx-auto my-0 text-uppercase">HOME</h1>
{% endblock %}

{% block contenido %}

        <!-- Masthead-->
        <header class="masthead">
          <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
              <div class="d-flex justify-content-center">
                  <div class="text-center">
                      <h1 class="mx-auto my-0 text-uppercase">HOME</h1>
                      <h2 class="text-white-50 mx-auto mt-2 mb-5">Pagina de inicio del sitio web</h2>
                      <a class="btn btn-primary" href="#about">Aceptar</a>
                      <a class="btn btn-primary" href={% url 'home:creararticulosapp' %}>Agregar Articulos</a>
                      <a class="btn btn-primary" href={% url 'home:crearcomentariosapp' %}>Agregar Comentarios</a>
                      <a class="btn btn-primary" href="#about">Cancelar</a>
                  </div>
              </div>
          </div>
      </header>
      <!-- About-->
      <section class="about-section text-center" id="about">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-lg-8">
                      <h2 class="text-white mb-4">Built with Bootstrap 5</h2>
                      <p class="text-white-50">
                          Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be yours right now, simply download the template on
                          <a href="https://startbootstrap.com/theme/grayscale/">the preview page.</a>
                          The theme is open source, and you can use it for any purpose, personal or commercial.
                      </p>
                  </div>
              </div>
              <img class="img-fluid" src="assets/img/ipad.png" alt="..." />
          </div>
      </section>
      <!-- Projects-->
      <section class="projects-section bg-light" id="projects">
          <div class="container px-4 px-lg-5">
              <!-- Featured Project Row-->
              <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                  <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="assets/img/bg-masthead.jpg" alt="..." /></div>
                  <div class="col-xl-4 col-lg-5">
                      <div class="featured-text text-center text-lg-left">
                          <h4>Shoreline</h4>
                          <p class="text-black-50 mb-0">Grayscale is open source and MIT licensed. This means you can use it for any project - even commercial projects! Download it, customize it, and publish your website!</p>
                      </div>
                  </div>
              </div>
              <!-- Project One Row-->
              <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                  <div class="col-lg-6"><img class="img-fluid" src="assets/img/demo-image-01.jpg" alt="..." /></div>
                  <div class="col-lg-6">
                      <div class="bg-black text-center h-100 project">
                          <div class="d-flex h-100">
                              <div class="project-text w-100 my-auto text-center text-lg-left">
                                  <h4 class="text-white">Misty</h4>
                                  <p class="mb-0 text-white-50">An example of where you can put an image of a project, or anything else, along with a description.</p>
                                  <hr class="d-none d-lg-block mb-0 ms-0" />
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <!-- Project Two Row-->
              <div class="row gx-0 justify-content-center">
                  <div class="col-lg-6"><img class="img-fluid" src="assets/img/demo-image-02.jpg" alt="..." /></div>
                  <div class="col-lg-6 order-lg-first">
                      <div class="bg-black text-center h-100 project">
                          <div class="d-flex h-100">
                              <div class="project-text w-100 my-auto text-center text-lg-right">
                                  <h4 class="text-white">Mountains</h4>
                                  <p class="mb-0 text-white-50">Another example of a project with its respective description. These sections work well responsively as well, try this theme on a small screen!</p>
                                  <hr class="d-none d-lg-block mb-0 me-0" />
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </section>
      

{% endblock %}

Proyectos/Ejemplo/EjemploA/Apps/home/templates/iniciosesion.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="{% static 'js/funciones.js' %}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Uriel Monterroso">
    <meta name="generator" content="    ">
    <title>Iniciar Sesion</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

</head>
<body>

    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="{% static 'assets/LogoUMG.png' %}" alt="" width="135" height="115">
    <h1 class="h3 mb-3 fw-normal">Iniciar Sesión</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Correo Electronico</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Contraseña</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Recuerdame
      </label>
    </div>
    <a href={% url 'home:homeapp' %} class="w-100 btn btn-lg btn-primary">Inciar Sesión</a>
    <p class="mt-5 mb-3 text-muted">&copy; Puede ingresar cualquier cosa</p>
  </form>

  <form action="" method="POST">
    <div class="form-floating">
      {% csrf_token %}
      {{ form.as_p }}
    </div>
    <input type="submit" name="submit">

  </form>

  <section class="signup-section" id="signup">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 mx-auto text-center">
                <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                
                <h2 class="text-white mb-5">Formulario de ingreso de Estudiantes</h2>

                <form class="form-signup" id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST">
                    <div class="text-white mb-5">
                        {% csrf_token %}
                        Usuario {{ form.usuario }}
                        Contrasena {{ form.contrasena }}
                    </div>    
                        <br><input type="submit" name="Guardar"> &nbsp; <a href={% url 'home:estudiantesapp' %}>Ver listado</a>
                </form>
            </div>
        </div>
    </div>
</section>


  <footer class="py-3 my-4">
    <p class="text-center text-muted">Ludim Monterroso  <br>  0903-19-22699</p>
  </footer>
</main>
</body>
</html>